import React from "react";

const sizeClasses = {
  txtMontserratMedium20: "font-medium font-montserrat",
  txtMontserratBold1331: "font-bold font-montserrat",
  txtMontserratRegular15Bluegray90001: "font-montserrat font-normal",
  txtMontserratMedium25: "font-medium font-montserrat",
  txtMontserratMedium24: "font-medium font-montserrat",
  txtRobotoRomanLight18: "font-light font-roboto",
  txtPoppinsSemiBold14Gray90002: "font-poppins font-semibold",
  txtMontserratMedium24Gray800: "font-medium font-montserrat",
  txtMontserratBold225Black9006c: "font-bold font-montserrat",
  txtMontserratBold4151Black900: "font-bold font-montserrat",
  txtPoppinsSemiBold14: "font-poppins font-semibold",
  txtMontserratSemiBold30: "font-montserrat font-semibold",
  txtMontserratBold40WhiteA700: "font-bold font-montserrat",
  txtMontserratBold225: "font-bold font-montserrat",
  txtMontserratMedium1973WhiteA700: "font-medium font-montserrat",
  txtMontserratMedium1973: "font-medium font-montserrat",
  txtRobotoRomanSemiBold20: "font-roboto font-semibold",
  txtMontserratBold3382WhiteA700: "font-bold font-montserrat",
  txtMontserratBold4756: "font-bold font-montserrat",
  txtMontserratBold2133: "font-bold font-montserrat",
  txtMontserratBold1681: "font-bold font-montserrat",
  txtMontserratRegular22Bluegray90001: "font-montserrat font-normal",
  txtMontserratBold20: "font-bold font-montserrat",
  txtRobotoRomanSemiBold8024: "font-roboto font-semibold",
  txtMontserratRegular11: "font-montserrat font-normal",
  txtMontserratBold1526: "font-bold font-montserrat",
  txtMontserratRegular52: "font-montserrat font-normal",
  txtMontserratRegular1331: "font-montserrat font-normal",
  txtMontserratBold1926: "font-bold font-montserrat",
  txtMontserratBold4756Black900: "font-bold font-montserrat",
  txtMontserratBold10176: "font-bold font-montserrat",
  txtMontserratBold393: "font-bold font-montserrat",
  txtMontserratRegular3626: "font-montserrat font-normal",
  txtMontserratRegular2856: "font-montserrat font-normal",
  txtRobotoRomanRegular15: "font-normal font-roboto",
  txtMontserratRegular1963: "font-montserrat font-normal",
  txtMontserratMedium1867: "font-medium font-montserrat",
  txtMontserratMedium25Gray600: "font-medium font-montserrat",
  txtMontserratRegular1526: "font-montserrat font-normal",
  txtMontserratMedium25WhiteA700: "font-medium font-montserrat",
  txtMontserratRegular12Bluegray700: "font-montserrat font-normal",
  txtPoppinsRegular20: "font-normal font-poppins",
  txtRobotoRomanSemiBold20Bluegray70001: "font-roboto font-semibold",
  txtRobotoRomanSemiBold35: "font-roboto font-semibold",
  txtMontserratBold2021: "font-bold font-montserrat",
  txtRobotoRomanRegular20Black900: "font-normal font-roboto",
  txtMontserratRegular225Black9006c: "font-montserrat font-normal",
  txtMontserratBold35: "font-bold font-montserrat",
  txtMontserratBold32: "font-bold font-montserrat",
  txtMontserratRegular22: "font-montserrat font-normal",
  txtMontserratBold20Gray90002: "font-bold font-montserrat",
  txtMontserratRegular20: "font-montserrat font-normal",
  txtRobotoRomanLight3415: "font-light font-roboto",
  txtMontserratRegular1963Black9006c: "font-montserrat font-normal",
  txtMontserratBold1838: "font-bold font-montserrat",
  txtRobotoRomanRegular20Bluegray70001: "font-normal font-roboto",
  txtMontserratRegular16: "font-montserrat font-normal",
  txtPoppinsRegular12: "font-normal font-poppins",
  txtMontserratSemiBold1838: "font-montserrat font-semibold",
  txtMontserratBold50Gray800: "font-bold font-montserrat",
  txtSegoeUI12: "font-normal font-segoeui",
  txtMontserratRegular14: "font-montserrat font-normal",
  txtMontserratRegular22WhiteA700: "font-montserrat font-normal",
  txtMontserratMedium25Black9006c: "font-medium font-montserrat",
  txtMontserratRegular15: "font-montserrat font-normal",
  txtMontserratRegular12: "font-montserrat font-normal",
  txtMontserratBold40: "font-bold font-montserrat",
  txtMontserratBold3382: "font-bold font-montserrat",
  txtMontserratRegular24WhiteA700: "font-montserrat font-normal",
  txtRobotoRomanRegular20: "font-normal font-roboto",
  txtMontserratMedium3893: "font-medium font-montserrat",
  txtMontserratRegular1838: "font-montserrat font-normal",
  txtMontserratRegular225Black900: "font-montserrat font-normal",
  txtMontserratBold4151: "font-bold font-montserrat",
  txtMontserratRegular16Gray9008e: "font-montserrat font-normal",
  txtMontserratMedium1684WhiteA700: "font-medium font-montserrat",
  txtMontserratRegular3256: "font-montserrat font-normal",
  txtMontserratBold295: "font-bold font-montserrat",
  txtMontserratSemiBold25: "font-montserrat font-semibold",
  txtSegoeUI22: "font-normal font-segoeui",
  txtSegoeUI20: "font-normal font-segoeui",
  txtRobotoRomanSemiBold15Bluegray70001: "font-roboto font-semibold",
  txtMontserratSemiBold20: "font-montserrat font-semibold",
  txtMontserratRegular15Blue900: "font-montserrat font-normal",
  txtMontserratRegular24: "font-montserrat font-normal",
  txtMontserratRegular225: "font-montserrat font-normal",
  txtMontserratSemiBold1867: "font-montserrat font-semibold",
  txtMontserratMedium1684: "font-medium font-montserrat",
  txtRobotoRomanSemiBold15: "font-roboto font-semibold",
  txtMontserratBold295Pink600: "font-bold font-montserrat",
  txtMontserratBold52: "font-bold font-montserrat",
  txtMontserratBold50: "font-bold font-montserrat",
  txtAmsterdamSignature65: "font-amsterdamsignature font-normal",
  txtRobotoRomanSemiBold15Blue900: "font-roboto font-semibold",
};

const Text = ({ children, className = "", size, as, ...restProps }) => {
  const Component = as || "p";

  return (
    <Component
      className={`text-left ${className} ${size && sizeClasses[size]}`}
      {...restProps}
    >
      {children}
    </Component>
  );
};

export { Text };
