import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/slide169one">Slide169One</Link>
        </li>
        <li>
          <Link to="/slide169two">Slide169Two</Link>
        </li>
        <li>
          <Link to="/slide169three">Slide169Three</Link>
        </li>
        <li>
          <Link to="/slide169four">Slide169Four</Link>
        </li>
        <li>
          <Link to="/slide169five">Slide169Five</Link>
        </li>
        <li>
          <Link to="/formone">FormOne</Link>
        </li>
        <li>
          <Link to="/formtwo">FormTwo</Link>
        </li>
        <li>
          <Link to="/formthree">FormThree</Link>
        </li>
        <li>
          <Link to="/formfour">FormFour</Link>
        </li>
        <li>
          <Link to="/formfive">FormFive</Link>
        </li>
        <li>
          <Link to="/formsix">FormSix</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
